# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  puts "If this is your first time here, go walk around the neighborhood as it can take a long time to download and provision the VM"

  config.vm.box = "box-cutter/ubuntu1604-desktop"

  config.vm.synced_folder "../share", "/home/vagrant/share"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true

#    vb.memory = 8192
    vb.memory = 4096
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--vram", "256"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

  config.vm.provision "shell", path: "do_privileged"

  config.vm.provision "shell", path: "do_unprivileged", privileged: false

end
